<a href="https://colab.research.google.com/github/pypankj30/Rebounce-Applied-AI-and-Analytics-Codes/blob/main/Python_301.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment MP3- Clean Analyse Summarise**

**Part 1 - Load and understand the data**

Importing pandas and numpy

In [2]:
import pandas as pd
import numpy as np

Loading data directly from web so that nothing loses when runtime restarts

In [3]:
url = "https://huggingface.co/datasets/aarav912/online-retail/resolve/main/online_retail.csv"
df = pd.read_csv(url)

Displaying first few rows

In [4]:
df.duplicated().sum()

np.int64(5268)

Checking the shape - how many rows and columns?

In [5]:
print(df.shape)
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

(541909, 8)
Number of rows: 541909
Number of columns: 8

Listing column names

In [6]:
print(df.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

Checking data types of each column

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

Counting missing values in every column

In [8]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Counting the duplicated rows

In [9]:
df.duplicated().sum()

np.int64(5268)

Description and CustomerID have null values , so they need cleaning

**Part 2- Clean the data**

In [27]:
#copy of clean original data
clean_df = df.copy()
print(clean_df.shape)

(541909, 8)

Keeping missing customerID becuase dropping them could impact overall data analysis as they are large in number

Checking data type of InvoiceDate

In [28]:
clean_df['InvoiceDate'].dtype

dtype('O')

Converting it to proper date time column from text

In [29]:
pd.to_datetime(clean_df['InvoiceDate'])

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 541909, dtype: datetime64[ns]

Dropping exact duplicates

In [30]:
clean_df = clean_df.drop_duplicates()
print(clean_df.shape)

(536641, 8)

Removing invalid transactions

In [31]:
clean_df = clean_df[(clean_df['Quantity'] > 0) & (clean_df['UnitPrice'] > 0)]
print(clean_df.shape)

(524878, 8)

Creating a new sales column

In [32]:
clean_df['Sales'] = clean_df['Quantity'] * clean_df['UnitPrice']
print(clean_df.shape)

(524878, 9)

**Part 3- NumPy analysis**

In [33]:
print(f"mean of sales: {np.mean(clean_df['Sales']):.2f}")
print(f"median of sales: {np.median(clean_df['Sales']):.2f}")
print(f"minimum of sales:{np.min(clean_df['Sales']):.2f}")
print(f"maximum of sales: {np.max(clean_df['Sales']):.2f}")
print(f"standard deviation of sales:{np.std(clean_df['Sales']):.2f}")

mean of sales: 20.28
median of sales: 9.92
minimum of sales:0.00
maximum of sales: 168469.60
standard deviation of sales:271.69

mean is almost twice of median , which tells us that sales are right skewed due to high value outliers

**Part 4- Pandas filtering**

1.transactions having sales above 500

In [34]:
print(f"Number of transactions having sales above 500: {clean_df[clean_df['Sales'] > 500].shape[0]}")

Number of transactions having sales above 500: 1155

10 largest transactions by sales?

In [37]:
largest_transactions = clean_df.sort_values('Sales', ascending=False)
print(f"largest transactions are:")
largest_transactions.head(10)

largest transactions are:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom,168469.60
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098.0,United Kingdom,38970.00
15017,537632,AMAZONFEE,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,NaN,United Kingdom,13541.33
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom,11062.06
173382,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029.0,United Kingdom,8142.75
348325,567423,23243,SET OF TEA COFFEE SUGAR TINS PANTRY,1412,2011-09-20 11:05:00,5.06,17450.0,United Kingdom,7144.72
160546,550461,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-04-18 13:20:00,2.10,15749.0,United Kingdom,6539.40
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-01-11 12:55:00,2.10,15749.0,United Kingdom,6539.40
421601,573003,23084,RABBIT NIGHT LIGHT,2400,2011-10-27 12:11:00,2.08,14646.0,Netherlands,4992.00

Transactions from Australia

In [39]:
print(f"Number of transactions from Australia: {clean_df[clean_df['Country'] == 'Australia'].shape[0]}")

Number of transactions from Australia: 1181

Transactions having quantity above 1000?

In [42]:
transaction_above_1000 = clean_df[clean_df['Quantity'] > 1000]
print(f"Number of transactions having quantity above 1000: {transaction_above_1000.shape[0]}")
transaction_above_1000.head()

Number of transactions having quantity above 1000: 106

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Sales
4850,536809,84950,ASSORTED COLOUR T-LIGHT HOLDER,1824,2010-12-02 16:48:00,0.55,15299.0,United Kingdom,1003.20
4945,536830,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,2880,2010-12-02 17:38:00,0.18,16754.0,United Kingdom,518.40
4946,536830,21915,RED HARMONICA IN BOX,1400,2010-12-02 17:38:00,1.06,16754.0,United Kingdom,1484.00
6365,536890,17084R,ASSORTED INCENSE PACK,1440,2010-12-03 11:48:00,0.16,14156.0,EIRE,230.40
16435,537659,22189,CREAM HEART CARD HOLDER,1008,2010-12-07 16:43:00,2.31,18102.0,United Kingdom,2328.48